/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eightgame;

import eightgame.Events.ResetListener;
import java.awt.Container;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import java.util.stream.IntStream;

/**
 *
 * @author Giuse
 */
public class EightBoard extends javax.swing.JFrame {
    private ArrayList<ResetListener> resetListeners = new ArrayList<ResetListener>();
    final int TILES_NUMBER = 9;
    final int TILE_SIZE = 35;
    final int TILE_OFFSET = 15;
    /**
     * Creates new form EightBoard
     */
    public EightBoard() {
        initComponents();
        initBoard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        eightController1 = new eightgame.EightController();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("FLIP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flipTiles(evt);
            }
        });

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBoard(evt);
            }
        });

        eightController1.setText("Start");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(eightController1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(eightController1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initBoard(){
        int[] permutation = generatePermutation(TILES_NUMBER);
        EightTile[] tiles = createTiles(TILES_NUMBER, permutation, TILE_OFFSET, TILE_SIZE);
        eightController1.setTiles(tiles);
        resetListeners.add(eightController1);
    }
    private int[] generatePermutation(int tilesNumber){
        //Creating an array that goes from 0 to n and then shuffle it
        int switchIndex,tempItem;
        int [] permutation = IntStream.rangeClosed(1, tilesNumber).toArray();
        Random rnd = new Random();
        
        for(int i = 0; i < tilesNumber - 1; i++){
            switchIndex = rnd.nextInt(tilesNumber - 1);
            
            tempItem =  permutation[i];
            permutation[i] = permutation[switchIndex];
            permutation[switchIndex] = tempItem;
        }
        
        return permutation;
    }
    private EightTile[] createTiles(int tilesNumber, int[] permutation, int tileOffset, int tileSize){
        EightTile[] tiles = new EightTile[tilesNumber];
        int tilesInARow = (int) Math.sqrt(tilesNumber);
        int gridSize = (tileSize + tileOffset) * tilesInARow;
        
        setSize(gridSize,gridSize + 100);
        
        for(int i = 0; i< tilesNumber; i++){
            tiles[i] = new EightTile(permutation[i],i);
            int positionX = (i * (tileSize + tileOffset)) % gridSize;
            int positionY = (i/tilesInARow) * (tileSize + tileOffset);
                        
            tiles[i].setLocation(new Point(positionX,positionY));
            tiles[i].setSize(tileSize, tileSize);
            getContentPane().add(tiles[i]);
            
            resetListeners.add(tiles[i]);
            
            tiles[i].addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    onTileClick(evt);
                }
            });

        }
        
        return tiles;
    }
    
    private void onTileClick(ActionEvent evt){
        EightTile sourceTile = (EightTile) evt.getSource();
        try{
            sourceTile.setLbl(9);
        }
        catch(Exception e){
            
        }
    }

    private void flipTiles(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flipTiles
        eightController1.switchTiles(0,1);
    }//GEN-LAST:event_flipTiles

    private void resetBoard(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBoard
        int[] permutation = generatePermutation(TILES_NUMBER);
        for(ResetListener listener : resetListeners){
            listener.reset(permutation);
        }
    }//GEN-LAST:event_resetBoard
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EightBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EightBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EightBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EightBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EightBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eightgame.EightController eightController1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
